import React from "react";
import Link from "next/link";

export const metadata = {
  title: "Code",
  descripton: "Generated by create next app",
  name: "Saikrishna488",
  content: "github, portfolio, saikrishna488, saikrishna",
  keywords:
    "developer, portfolio, github, saikrishna488, saikrishna, saikrishna488.github.io, saikrishna488.git, nextjs, reactjs, nodejs, expressjs, mongodb, mysql, javascript, html, css, php, python, bash, c, c++, java, fullstack, web, data, data-driven, open-source, hackathon, coding, challenge, communication, collaboration, diversity, tech, tools, trends, projects, personal, reading, coding, skills, sharp, improve, learn, others, check, out, github, profile, work, projects, home, about, code, contact, contact me, contact me page, contact page, contact me page, contact me page,",
};

const fetchRepos = async () => {
  const res = await fetch("https://api.github.com/users/saikrishna488/repos",{ cache: 'no-store' });
  const data = await res.json();
  return data;
};

const page = async () => {
  const repos = await fetchRepos();
  return (
    <>
      <div className="container">
        <ul>
          {repos.map((repo) => (
            <li key={repo.id}>
              <h2>{repo.name}</h2>
              <p>
                {repo.description
                  ? repo.description.length > 160
                    ? repo.description.slice(0, 160) + "...."
                    : repo.description
                  : "No description"}
              </p>
              <div>
                {" "}
                <b>Watchers : {repo.watchers}</b>{" "}
                <b>stars : {repo.stargazers_count}</b>
              </div>
              <div className="btn-con">
                <Link id="btn" target="_blank" href={repo.html_url}>
                  Visit Repo
                </Link>
              </div>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
};

export default page;
