import React from "react";
import Link from "next/link";

export const metadata = {
  title: "About",
  descripton: "Generated by create next app",
  name : 'Saikrishna488',
  content : 'github, portfolio, saikrishna488, saikrishna',
  keywords : 'developer, portfolio, github, saikrishna488, saikrishna, saikrishna488.github.io, saikrishna488.git, nextjs, reactjs, nodejs, expressjs, mongodb, mysql, javascript, html, css, php, python, bash, c, c++, java, fullstack, web, data, data-driven, open-source, hackathon, coding, challenge, communication, collaboration, diversity, tech, tools, trends, projects, personal, reading, coding, skills, sharp, improve, learn, others, check, out, github, profile, work, projects, home, about, code, contact, contact me, contact me page, contact page, contact me page, contact me page,'
};

const page = () => {
  return (
    <>
      <div className="container">
        <p>
          Hi, I'm Saikrishna - a computer science engineering student with a
          passion for building projects and exploring new technologies. My
          diverse skill set includes proficiency in multiple programming
          languages, such as C, C++, Java, HTML, CSS, PHP, JavaScript, React,
          Next.js, Node.js, Express, MongoDB, MySQL, Bash, and Python. I love
          contributing to open-source projects and collaborating with other
          developers to build impactful applications. My interests include
          full-stack development, web development, and data-driven applications.
          I'm always on the lookout for new tools and technologies to add to my
          toolkit, and I enjoy participating in hackathons and coding challenges
          to keep my skills sharp. When I'm not coding, you can find me reading
          about the latest trends in tech or working on personal projects. I
          value communication, collaboration, and diversity in tech, and I'm
          always looking for ways to improve my skills and learn from others.
          Feel free to check out my GitHub profile to see some of my work and
          projects. <br/>
        </p>
        <div className="btn-con">
            <Link id="btn" href='https://github.com/saikrishna488'>Github</Link>
            <Link id="btn" href='https://instagram.com/captenium'>Instagram</Link>
            <Link id="btn" href='https://t.me/captain488'>Telegram</Link>
        </div>
      </div>
    </>
  );
};

export default page;
