import Header from './components/Header'
import Script from 'next/script'
import './globals.css'

export const metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
  name : 'Saikrishna488',
  content : 'github, portfolio, saikrishna488, saikrishna',
  keywords : 'developer, portfolio, github, saikrishna488, saikrishna, saikrishna488.github.io, saikrishna488.git, nextjs, reactjs, nodejs, expressjs, mongodb, mysql, javascript, html, css, php, python, bash, c, c++, java, fullstack, web, data, data-driven, open-source, hackathon, coding, challenge, communication, collaboration, diversity, tech, tools, trends, projects, personal, reading, coding, skills, sharp, improve, learn, others, check, out, github, profile, work, projects, home, about, code, contact, contact me, contact me page, contact page, contact me page, contact me page,'
}
export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
    <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4956894271613471"
     crossorigin="anonymous"></Script>
      <body >
        <Header/>
        {children}
      </body>
    </html>
  )
}
